wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/AnnotatedFeatures.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/MotifFeatures.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_CD4.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_GM06990.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_GM12878.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_H1ESC.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_HeLa-S3.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_HepG2.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_HMEC.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_HSMM.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_HUVEC.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_IMR90.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_K562.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_MultiCell.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_NH-A.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/RegulatoryFeatures_NHEK.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/Segmentation_GM12878.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/Segmentation_H1ESC.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/Segmentation_HeLa-S3.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/Segmentation_HepG2.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/Segmentation_HUVEC.gff.gz
wget ftp://ftp.ensembl.org/pub/release-75/regulation/homo_sapiens/Segmentation_K562.gff.gz
