samtools index CP1-iPS_biorep2.bam
samtools index CP7_biorep1.bam
samtools index CP7_biorep2.bam
samtools index FCP1-B_biorep1.bam
samtools index FCP1-B_biorep2.bam
samtools index Double-KO_biorep1_primaryP4.bam
samtools index ENGase-KO_biorep1_primaryP4.bam
samtools index NGLY1-KO_biorep1_immortP3_2014.11.24.bam
samtools index CP1-NPC-A2_biorep1.bam
samtools index CP1-NPC-A2_biorep2.bam
samtools index CP1-NPC-A3_biorep1.bam
samtools index CP1-NPC-A3_biorep2.bam
