samtools index CP1-B_biorep1_lane3.bam
samtools index CP1-B_biorep2_lane3.bam
samtools index CP1-iPS_biorep1.bam
samtools index CP3-B_biorep1_lane3.bam
samtools index CP3-B_biorep2_lane3.bam
samtools index Ctrl-B_biorep1_lane3.bam
samtools index Ctrl-B_biorep2_lane3.bam
samtools index Double-KO_biorep1_immortP3.bam
samtools index Double-KO_biorep1_immortP5.bam
samtools index Double-KO_biorep1_primaryP4.bam
samtools index Double-KO_biorep2_immortP3.bam
samtools index Double-KO_biorep2_immortP5.bam
samtools index Double-KO_biorep2_primaryP4.bam
samtools index ENGase-KO_biorep1_immortP3.bam
samtools index ENGase-KO_biorep1_immortP5.bam
samtools index ENGase-KO_biorep1_primaryP4.bam
samtools index ENGase-KO_biorep2_immortP3.bam
samtools index ENGase-KO_biorep2_immortP5.bam
samtools index FCP1-iPS_biorep1.bam
samtools index FCP1-iPS_biorep2.bam
samtools index MCP1-B_biorep1_lane3.bam
samtools index MCP1-B_biorep2_lane3.bam
samtools index MCP1-iPS_biorep1.bam
samtools index MCP1-iPS_biorep2.bam
samtools index NGLY1-KO_biorep1_immortP3.bam
samtools index NGLY1-KO_biorep1_immortP5.bam
samtools index Ngly1-KO_biorep1_primaryP4.bam
samtools index NGLY1-KO_biorep1_primaryP4.bam
samtools index NGLY1-KO_biorep2_immortP5.bam
samtools index Ngly1-KO_biorep2_primaryP4.bam
samtools index NGLY1-KO_biorep2_primaryP4.bam
samtools index Ngly1-KO_biorep3_primaryP4.bam
samtools index NGLY1-KO_biorep3_primaryP4.bam
samtools index WT_biorep1_immortP3.bam
samtools index WT_biorep1_immortP5.bam
samtools index WT_biorep1_primaryP4.bam
samtools index WT_biorep2_immortP3.bam
samtools index WT_biorep2_immortP5.bam
samtools index WT_biorep2_primaryP4.bam
samtools index WT_biorep3_immortP3.bam
samtools index WT_biorep3_immortP5.bam
samtools index WT_biorep3_primaryP4.bam
