library(ggplot2)
library(reshape2)
rt =read.table('CDx-reads-count.curated')
data=cbind(CD=c("CD40","CD21"),rt)
melted <- melt(data, id.vars=c("CD"))
colnames(melted)=c("CD Protein","Sample","value")
#qplot(x=ordered(as.factor(Sample),c('CP1-B','CP3-B','MCP1-B','Ctrl-B')), y='Reads Count', data=rt, geom="bar", stat="identity",position="dodge", fill="white",colour="darkgreen")
#qplot(x=Sample, y=Count, data=rt, geom="bar", stat="identity",position="dodge")
pdf('CDx-in-Bcells.pdf')
#c <- ggplot(melted, aes(x=factor(Sample, levels=c('CP1','CP2','CP3','CP4','FCP1','MCP1')),y=value),fill=variable)
#c + geom_bar(stat="identity", width=0.7) + ylab("The number of reads from human herpesvirus 4 (EBV)") + xlab("Sample of B cells")
#dev.off()
qplot(x=factor(Sample, levels=c('CP1_rep1','CP1_rep2','CP3_rep1','CP3_rep2','MCP1_rep1','MCP1_rep2','Ctrl_rep1','Ctrl_rep2')), y=value, fill=`CD Protein`,data=melted, geom="bar", stat="identity",position="dodge",xlab="Sample of B cells", ylab="Number of reads")
dev.off()

                                                    
