qsub 19_AzaC_20uM_biorep1.bam.mpileup.sh
qsub 19_AzaC_20uM_biorep2.bam.mpileup.sh
qsub 19_DMSO_biorep1.bam.mpileup.sh
qsub 19_DMSO_biorep2.bam.mpileup.sh
qsub CP1_AzaC_20uM_biorep1.bam.mpileup.sh
qsub CP1_AzaC_20uM_biorep2.bam.mpileup.sh
qsub CP1_DMSO_biorep1.bam.mpileup.sh
qsub CP1_DMSO_biorep2.bam.mpileup.sh
qsub CP2_AzaC_20uM_biorep1.bam.mpileup.sh
qsub CP2_AzaC_20uM_biorep2.bam.mpileup.sh
qsub CP2_DMSO_biorep1.bam.mpileup.sh
qsub CP2_DMSO_biorep2.bam.mpileup.sh
qsub CP3_AzaC_20uM_biorep1.bam.mpileup.sh
qsub CP3_AzaC_20uM_biorep2.bam.mpileup.sh
qsub CP3_DMSO_biorep1.bam.mpileup.sh
qsub CP3_DMSO_biorep2.bam.mpileup.sh
qsub FCP1_AzaC_20uM_biorep1.bam.mpileup.sh
qsub FCP1_AzaC_20uM_biorep2.bam.mpileup.sh
qsub FCP1_DMSO_biorep1.bam.mpileup.sh
qsub FCP1_DMSO_biorep2.bam.mpileup.sh
qsub MCP1_AzaC_20uM_biorep1.bam.mpileup.sh
qsub MCP1_AzaC_20uM_biorep2.bam.mpileup.sh
qsub MCP1_DMSO_biorep1.bam.mpileup.sh
qsub MCP1_DMSO_biorep2.bam.mpileup.sh
