ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.adrenal.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.brain.1.filtered.sorted.bam.bai .
ln -s /g/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.ovary.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.breast.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.kidney.1.filtered.sorted.bam.bai .
ln -s /g/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/restOfFiltered2/GRCh37.HumanBodyMap.thyroid.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/restOfFiltered/GRCh37.HumanBodyMap.lymph.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.heart.1.filtered.sorted.bam.bai .
ln -s /g/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/restOfFiltered2/GRCh37.HumanBodyMap.testes.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.adipose.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.lung.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/restOfFiltered/GRCh37.HumanBodyMap.prostate.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.colon.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.blood.1.filtered.sorted.bam.bai .
ln -s /g/tier2/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/preAligned/GRCh37.HumanBodyMap.liver.1.filtered.sorted.bam.bai .
ln -s /g/steinmetz/project/mTEC_Seq/externalData/IlluminaBodyMap/restOfFiltered2/GRCh37.HumanBodyMap.skeletal_muscle.1.filtered.sorted.bam.bai .
